### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by modemgeek** [sjkp/letsencrypt-siteextension#107]
I've instaled this on 40 webapps and have generated over 500 certificates with no issues.  However on one particular pod I get this error when requesting a certificate.  Tried different domains and it just errors right away.  I've tried uninstalled and reinstalling the extension but haven't able to get around this 400 error.  

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.WebException: The remote server returned an error: (400) Bad Request.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[WebException: The remote server returned an error: (400) Bad Request.]
   System.Net.HttpWebRequest.GetResponse() +1743
   ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) +770

[AcmeWebException: Unexpected error]
   ACMESharp.AcmeClient.Register(String[] contacts) +679
   LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:263
   LetsEncrypt.SiteExtension.Controllers.HomeController.Install(RequestAndInstallModel model) +755
   lambda_method(Closure , ControllerBase , Object[] ) +139
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +71
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

**Comment by sjkp** [comment]
Could this be related to #87?

**Comment by modemgeek** [comment]
I looked over that issue and no, there are no special characters.  All hostnames are in English using alpha-numeric only.

**Comment by modemgeek** [comment]
I opened a case with Microsoft to see if they could shed some light on the error message.  Here is what they provided.  They said they couldn't get any more information because they can't get into the DLL of third party extension.  Not sure if this would provide any help.

Response from Microsoft support:
As discussed on the phone, FREB gives HTTP 500 in ManagedPipeline Handler of the Kudu SiteName="~obfuscated"
Url="/letsencrypt/Home/Install"

Here is our Mini FREB

|#90 HANDLER_CHANGED @0ms
OldHandler: ExtensionlessUrlHandler-Integrated-4.0, NewHandler: System.Web.Mvc.MvcHandler, NewHandlerType: System.Web.Mvc.MvcHandler, System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
|#100 NOTIFY_MODULE_START @0ms
Module: ManagedPipelineHandler, Notification: EXECUTE_REQUEST_HANDLER
|#101 GENERAL_READ_ENTITY_START @0ms
|#102 GENERAL_READ_ENTITY_END @0ms
BytesReceived: 217, ErrorCode: 0x0|#106 MODULE_SET_RESPONSE_STATUS_ERROR @2984ms
Module: ManagedPipelineHandler, Notification: EXECUTE_REQUEST_HANDLER, Status: 500, SubStatus: 0, HttpReason: Internal Server Error, Win32ErrorCode: 0x00000000, ConfigException: 
|#107 NOTIFY_MODULE_END @2984ms

**Comment by sjkp** [comment]
Doesn't really help much. But looking at the exception again I can see that it actually fails at the registration step. Which email are you using for registering. If you dont want to provide it here, send me an email at mail@sjkp.dk

**Comment by ericebarker** [comment]
I am having a similar but possibly different issue with the cert generation. The webjobs functions show success but do not install and seem to be running too often:  
```
[03/30/2017 02:44:59 > 321ba4: ERR ] 
[03/30/2017 02:44:59 > 321ba4: ERR ] Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: '{{SITE}}.queue.core.windows.net' ---> System.Net.WebException: The remote name could not be resolved: '{{SITE}}.queue.core.windows.net'
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
[03/30/2017 02:44:59 > 321ba4: ERR ]    --- End of inner exception stack trace ---
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
[03/30/2017 02:44:59 > 321ba4: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.<ExecuteAsync>d__4.MoveNext()
[03/30/2017 02:44:59 > 321ba4: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[03/30/2017 02:44:59 > 321ba4: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/30/2017 02:44:59 > 321ba4: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[03/30/2017 02:44:59 > 321ba4: ERR ]    at System.Threading.ThreadHelper.ThreadStart()
[03/30/2017 02:45:00 > 321ba4: SYS ERR ] Job failed due to exit code -532462766
[03/30/2017 02:45:00 > 321ba4: SYS INFO] Process went down, waiting for 60 seconds
[03/30/2017 02:45:00 > 321ba4: SYS INFO] Status changed to PendingRestart
[03/30/2017 02:46:00 > 321ba4: SYS INFO] Run script 'LetsEncrypt.SiteExtension.WebJob.exe' with script host - 'WindowsScriptHost'
[03/30/2017 02:46:00 > 321ba4: SYS INFO] Status changed to Running
[03/30/2017 02:46:02 > 321ba4: INFO] Found the following functions:
[03/30/2017 02:46:02 > 321ba4: INFO] LetsEncrypt.SiteExtension.Functions.SetupHostNameAndCertificate
[03/30/2017 02:46:02 > 321ba4: INFO] LetsEncrypt.SiteExtension.Functions.RenewCertificate
[03/30/2017 02:46:02 > 321ba4: INFO] Executing: 'Functions.RenewCertificate' - Reason: 'Timer fired at 2017-03-30T02:46:02.7106326+00:00'
[03/30/2017 02:46:03 > 321ba4: INFO] Renew certificate
[03/30/2017 02:46:03 > 321ba4: INFO] Executing: 'Functions.SetupHostNameAndCertificate' - Reason: 'Timer fired at 2017-03-30T02:46:02.6654612+00:00'
[03/30/2017 02:46:03 > 321ba4: INFO] Starting setup hostname and certificate
[03/30/2017 02:46:03 > 321ba4: INFO] Completed setup hostname and certificate
[03/30/2017 02:46:04 > 321ba4: INFO] Executed: 'Functions.SetupHostNameAndCertificate' (Succeeded)
[03/30/2017 02:46:04 > 321ba4: INFO] Completed renewal of '0' certificates
[03/30/2017 02:46:04 > 321ba4: INFO] Executed: 'Functions.RenewCertificate' (Succeeded)
[03/30/2017 02:46:04 > 321ba4: INFO] Job host started  
```

When I attempt to run from /letsencrypt/Home/Install, I get this System Exception:  

```
[WebException: The remote server returned an error: (429) Unknown.]
   System.Net.HttpWebRequest.GetResponse() +1399
   ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) +642

[AcmeWebException: Unexpected error]
   ACMESharp.AcmeClient.RequestCertificate(String csrContent) +377
   LetsEncrypt.SiteExtension.Core.CertificateManager.GetCertificate(Target binding) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:319
   LetsEncrypt.SiteExtension.Core.CertificateManager.Auto(Target binding) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:463
   LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:263
   LetsEncrypt.SiteExtension.Controllers.HomeController.Install(RequestAndInstallModel model) +649
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +169
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9765121
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155  
```

I see the 429 code for too many requests, and it appears my webjobs are firing those functions very frequently. I am going to try turning off the webjob for a few days and then spin it back up, but if you see anything that jumps out as obvious I'd love to hear your thoughts.  

Thanks!

**Comment by sjkp** [comment]
There's some code in the https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.SiteExtension.Test/CleanupCertificates.cs test that you can look at for inspiration on how to parallelize the clean up process.

**Comment by modemgeek** [comment]
Issue no longer happens
