### ISSUE TITLE
Functions.RenewCertificate always fails

### ISSUE THREAD

**Issue by haldyr** [sjkp/letsencrypt-siteextension#142]
Functions.RenewCertificate always fails with following stacktrace:
`Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> System.Exception: The Lets Encrypt ACME server was probably unable to reach http://ckzije.cz/.well-known/acme-challenge/am6LvG_TKU8Ici6XHGOikosLeg717ezgPZfV56EOp4k view error report from Lets Encrypt at https://acme-v01.api.letsencrypt.org/acme/authz/2jq1J0lXshE2fK6uBsZOjQrJd2-bNJLAvKH3JMrGQvo for more information
 at LetsEncrypt.SiteExtension.Core.Services.BaseAuthorizationChannelgeProvider.<Authorize>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\BaseAuthorizationChannelgeProvider.cs:line 106
 --- End of stack trace from previous location where exception was thrown ---
 at LetsEncrypt.SiteExtension.Core.Services.BaseAuthorizationChannelgeProvider.<Authorize>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\BaseAuthorizationChannelgeProvider.cs:line 131
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:line 39
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.<RequestAndInstallInternalAsync>d__10.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 150
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.<RenewCertificate>d__8.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 117
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Functions.<RenewCertificate>d__1.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 61
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of inner exception stack trace ---
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()`

It seems like acme challenge does not exists but it does! 
I was able to renew www.ckzije.cz but not ckzije.cz. We have some redirects there so I turned them off:
`<rule name="Allow LetsEncrypt" patternSyntax="Wildcard" stopProcessing="true">
  <match url=".well-known/*" />
  <action type="None" />
</rule>`
But still the same error appears...

**Comment by sjkp** [comment]
IT seems like lets encrypts servers are getting access denied 403 (https://acme-v01.api.letsencrypt.org/acme/authz/2jq1J0lXshE2fK6uBsZOjQrJd2-bNJLAvKH3JMrGQvo). Do you have some auth setup that you forgot to disable for the .well-known directory

**Comment by haldyr** [comment]
It is weird since URL is accessible in anonymous window in browser - see:
http://ckzije.cz/.well-known/acme-challenge/am6LvG_TKU8Ici6XHGOikosLeg717ezgPZfV56EOp4k

Let's Encrypt somehow cannot validate ACME challlenge, but it is there...

**Comment by sjkp** [comment]
Try to ask on the Let's Encrypt support forum, there must be a reason why it is getting unauthorized unless you changed something recently with your website.

**Comment by sjkp** [comment]
@haldyr did you figure out what was causing this?

**Comment by maxkonyukh** [comment]
Have the same problem currently. What the problem was?

**Comment by cryptcoin-junkey** [comment]
I got an similar error today.
In my case, my APi server instance kept return empty responses like this.

```
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: -1
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
< Date: Thu, 29 Mar 2018 04:32:16 GMT
< Content-Length: 0
<
```

And it was fixed after patching `letsencrypt` functtion like this.

```
      context.res = {
        status: 200,
        headers: { "Content-Type": "text/plain" },
        body: data,
        isRaw: true
      };
      context.done();
```

```
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 87
< Content-Type: text/plain
< Expires: -1
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
< Date: Thu, 29 Mar 2018 04:39:32 GMT
<
* Connection #0 to host api.monaparty.me left intact
12A6K44mK48xtmrpG88ZwnHC3xwRKUadJJzhsUwsDhY.dEoG29pT6XqyLjNdFNpJTH0EtOKNZIFwJSRADtfbH24
```

The original code doesn't work well even though it should be worked (referring to the official document).

**Comment by haldyr** [comment]
Sorry for late reply.
Problem was caused by AAAA DNS record (for IPv6) for that domain.

There was nothing wrong with the web app itself. Just misconfigured DNS - A record for fine but someone forgot to update/remove AAAA record 😃
