### ISSUE TITLE
missing x64\libeay32.dll

### ISSUE THREAD

**Issue by buchizo** [sjkp/letsencrypt-siteextension#143]
I using this x64 versions site extension on Azure Web Apps (x64). Unfortunately, Functions.RenewCertificate was always failed, because System.DllNotFoundException: Unable to load DLL 'x64\libeay32'.

**Exception**:
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ACMESharp.PKI.Providers.OpenSslLibBaseProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'x64\libeay32': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
 at OpenSSL.Core.Native.SSLeay()
 at OpenSSL.Core.Version.get_Library()
 at OpenSSL.Core.Native..cctor()
 --- End of inner exception stack trace ---
 at OpenSSL.Core.Native.BN_new()
 at OpenSSL.Core.BigNumber.op_Implicit(UInt32 value)
 at ACMESharp.PKI.Providers.OpenSslLibBaseProvider..cctor()
 --- End of inner exception stack trace ---
 at ACMESharp.PKI.Providers.OpenSslLibBaseProvider..ctor(IReadOnlyDictionary`2 initParams)
 at ACMESharp.PKI.Providers.OpenSslLib64Provider..ctor(IReadOnlyDictionary`2 initParams)
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
 at ACMESharp.PKI.Providers.OpenSslLibProvider..ctor(IReadOnlyDictionary`2 newParams)
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
 at ACMESharp.PKI.CertificateProvider.GetProvider(String name, IReadOnlyDictionary`2 initParams)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.GetCertificate(Target binding)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.Auto(Target binding)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target)
 at LetsEncrypt.SiteExtension.Core.CertificateManager.<RenewCertificate>d__7.MoveNext()
 at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
 at LetsEncrypt.SiteExtension.Functions.RenewCertificate(TimerInfo timerInfo)
 at lambda_method(Closure , Functions , Object[] )
 at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of inner exception stack trace ---
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()

**Workaround**:
libeay32.dll copy from "D:\home\SiteExtensions\letsencrypt64\bin\x64\*.dll" to  "D:\home\site\wwwroot\App_Data\jobs\continuous\letsencrypt64(letsencrypt.siteextension.job)\x64" on Kudu.

I guess these assemblies isn't include in siteextension package.

**Comment by sjkp** [comment]
thanks for the heads up, that is definitely not intended.

**Comment by sjkp** [comment]
Next version will remove the dependency on OpenSSL and thus it will no longer be required to have both a x86 and x64 version, which should prevent problems like this in the future.

**Comment by rewatiUpadhyay007** [comment]
is this resolved in any version?
