### ISSUE TITLE
Https Encryption stops working after a certain time

### ISSUE THREAD

**Issue by tiagorz** [sjkp/letsencrypt-siteextension#149]
Hi,
I'm using LetsEncrypt for my website The script was installed on the azure and was running until yesterday. But suddenly it stopped working and in the azure it's all set up. I have renewed it to see if it works, but it does not work anymore. Can someone help me?

**Comment by sjkp** [comment]
You can send me a mail mail@sjkp.dk with your domain name, then I can get back to you via mail. If you dont want to post it here.

**Comment by stebueh** [comment]
I am experiencing similar problems, too. For a couple of Azure Web Apps, LetsEncrypt has been running seamlessly for months now.

Today, I started having problems issuing certificates for a new web app, and when I checked the log for existing apps, I found the following:

`[06/30/2017 07:00:27 > 3006db: INFO] Executed: 'Functions.AddCertificate' (Succeeded)
[06/30/2017 07:00:27 > 3006db: INFO]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '0a7f4d55-09d5-4969-8233-6b84db39b773'
[06/30/2017 07:00:27 > 3006db: INFO] Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.
[06/30/2017 07:00:27 > 3006db: INFO] Trace ID: f87675ea-d33f-4821-a234-1c6c41400800
[06/30/2017 07:00:27 > 3006db: INFO] Correlation ID: c09dab17-5849-4573-9c7f-2c4da315b3cd
[06/30/2017 07:00:27 > 3006db: INFO] Timestamp: 2017-06-30 07:00:27Z ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
[06/30/2017 07:00:27 > 3006db: INFO]    at System.Net.HttpWebRequest.GetResponse()
[06/30/2017 07:00:27 > 3006db: INFO]    at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
[06/30/2017 07:00:27 > 3006db: INFO] --- End of stack trace from previous location where exception was thrown ---
[06/30/2017 07:00:27 > 3006db: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[06/30/2017 07:00:28 > 3006db: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/30/2017 07:00:28 > 3006db: INFO]    at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
[06/30/2017 07:00:28 > 3006db: INFO]    --- End of inner exception stack trace ---
[06/30/2017 07:00:28 > 3006db: INFO]    at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
[06/30/2017 07:00:28 > 3006db: INFO]    at LetsEncrypt.SiteExtension.ArmHelper.GetToken(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 30
[06/30/2017 07:00:28 > 3006db: INFO]    at LetsEncrypt.SiteExtension.ArmHelper.GetWebSiteManagementClient(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 18
[06/30/2017 07:00:28 > 3006db: INFO]    at LetsEncrypt.SiteExtension.Core.Services.KuduFileSystemAuthorizationChallengeProvider..ctor(IAzureEnvironment azureEnvironment, IAuthorizationChallengeProviderConfig config) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\KuduFileSystemAuthorizationChallengeProvider.cs:line 23
[06/30/2017 07:00:28 > 3006db: INFO]    at LetsEncrypt.SiteExtension.Core.CertificateManager..ctor(AppSettingsAuthConfig config) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 31
[06/30/2017 07:00:28 > 3006db: INFO]    at LetsEncrypt.SiteExtension.Functions.<RenewCertificate>d__1.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 61`

My guess is that it might be an issue of Azure AD.

**Comment by tiagorz** [comment]
Hello
I discovered my problem. I configured the DNS with record A pointing to the Azure IP.
For some reason the azure has changed the IP and lets encrypt stopped working. I've changed the DNS for CNAME pointing to mydomain.azurewebsites.net. And so it worked

**Comment by stebueh** [comment]
I re-created the applications in Azure AD, created a service principal and granted it the contributor role; seems to be working again.

**Comment by sjkp** [comment]
Good to hear that you both found a fix. I will close this this issue, feel free to open a new one, if you encounter other errors.
