### ISSUE TITLE
RenewCertificate job fails

### ISSUE THREAD

**Issue by hefp88** [sjkp/letsencrypt-siteextension#162]
Hello,

We've successfully retrieved a certificate using the Let's Encrypt extension past May. Yesterday was 14 days before expiration, so we checked if it was renewed, but unfortunately it wasn't. When checking in the Azure Portal, we discovered both the web jobs and extension were removed from our app service. No idea how this happened, but we reinstalled the extension and then also the web jobs were recreated.

But now the RenewCertificate job step keeps failing (error message below). The extension seems to be working correctly, because we can see the values from the app service settings in the extension site. 

The RenewCertificate step did run successfully before the Let's Encrypt extension was removed.

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> System.NullReferenceException: Object reference not set to an instance of an object.
 at LetsEncrypt.Azure.Core.CertificateManager.<RenewCertificate>d__8.MoveNext() in C:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 110
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Functions.<RenewCertificate>d__1.MoveNext() in C:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 66
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of inner exception stack trace ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__10.MoveNext()
```

What can we do to resolve this issue?

Kind regards

**Comment by sjkp** [comment]
That is most unfortunate. I think that the settings.json file that is created at the first manual install might also have been deleted together with the web jobs. Can you check through the kudu portal that there is a settings file in: D:\home\data\letsencrypt and that it is not empty? 
If the file is gone, the renew web job will miss some values e.g. the email unless you have added all the app settings manually. 

The easiest why to fix it, is to run the installation manually, that will recreate the settings file.

**Comment by hefp88** [comment]
Thanks! The settings file was indeed gone.

I've ran the installation manually and the settings file was recreated.

**Comment by ohadschn** [comment]
Could this be a duplicate of https://github.com/sjkp/letsencrypt-siteextension/issues/34?
