### ISSUE TITLE
WebJobs not working

### ISSUE THREAD

**Issue by masikmos** [sjkp/letsencrypt-siteextension#181]
WebJobs not work after update to 0.8.5

`[11/22/2017 14:15:01 > dd716a: SYS INFO] Status changed to Running
[11/22/2017 14:15:02 > dd716a: ERR ] 
[11/22/2017 14:15:02 > dd716a: ERR ] Unhandled Exception: System.InvalidOperationException: Microsoft Azure WebJobs SDK 'Dashboard' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:
[11/22/2017 14:15:02 > dd716a: ERR ] 1. Set the connection string named 'AzureWebJobsDashboard' in the connectionStrings section of the .config file in the following format <add name="AzureWebJobsDashboard" connectionString="DefaultEndpointsProtocol=http|https;AccountName=NAME;AccountKey=KEY" />, or
[11/22/2017 14:15:02 > dd716a: ERR ] 2. Set the environment variable named 'AzureWebJobsDashboard', or
[11/22/2017 14:15:02 > dd716a: ERR ] 3. Set corresponding property of JobHostConfiguration.
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.StorageAccountParser.ParseAccount(String connectionString, String connectionStringName, IServiceProvider services)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.get_DashboardAccount()
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<TryGetAccountAsync>d__23.MoveNext()
[11/22/2017 14:15:02 > dd716a: ERR ] --- End of stack trace from previous location where exception was thrown ---
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__5.MoveNext()
[11/22/2017 14:15:02 > dd716a: ERR ] --- End of stack trace from previous location where exception was thrown ---
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__4.MoveNext()
[11/22/2017 14:15:02 > dd716a: ERR ] --- End of stack trace from previous location where exception was thrown ---
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__44.MoveNext()
[11/22/2017 14:15:02 > dd716a: ERR ] --- End of stack trace from previous location where exception was thrown ---
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__27.MoveNext()
[11/22/2017 14:15:02 > dd716a: ERR ] --- End of stack trace from previous location where exception was thrown ---
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.JobHost.Start()
[11/22/2017 14:15:02 > dd716a: ERR ]    at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
[11/22/2017 14:15:02 > dd716a: ERR ]    at LetsEncrypt.SiteExtension.WebJob.Program.Main() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Program.cs:line 28
[11/22/2017 14:15:02 > dd716a: SYS ERR ] Job failed due to exit code -532462766
[11/22/2017 14:15:02 > dd716a: SYS INFO] Process went down, waiting for 60 seconds
[11/22/2017 14:15:02 > dd716a: SYS INFO] Status changed to PendingRestart
[11/22/2017 14:15:03 > 5dada1: SYS INFO] Run script 'LetsEncrypt.SiteExtension.WebJob.exe' with script host - 'WindowsScriptHost'
[11/22/2017 14:15:03 > 5dada1: SYS INFO] Status changed to Running
[11/22/2017 14:15:03 > dd716a: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[11/22/2017 14:15:03 > dd716a: SYS INFO] Status changed to Stopping
[11/22/2017 14:15:04 > 5dada1: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[11/22/2017 14:15:04 > 5dada1: SYS INFO] Status changed to Stopping
[11/22/2017 14:15:03 > dd716a: SYS INFO] Status changed to Stopped
[11/22/2017 14:15:03 > dd716a: SYS INFO] Status changed to Starting
[11/22/2017 14:15:03 > dd716a: SYS INFO] Run script 'LetsEncrypt.SiteExtension.WebJob.exe' with script host - 'WindowsScriptHost'
[11/22/2017 14:15:03 > dd716a: SYS INFO] Status changed to Running
[11/22/2017 14:15:04 > 5dada1: ERR ] 
[11/22/2017 14:15:04 > 5dada1: ERR ] Unhandled Exception: System.InvalidOperationException: Microsoft Azure WebJobs SDK 'Dashboard' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:`

and this loop error

status webjobs "pending restart"

**Comment by sjkp** [comment]
Did you do add the connection strings as described here:
https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install#azure-web-jobs

**Comment by masikmos** [comment]
now i hawe 

> Site extensions can be installed from the Gallery.

and all my extensions have been deleted!

**Comment by masikmos** [comment]
ok i fix that, just restart web app and reinstall extension, but i don't understand where i need fix my web job?????

**Comment by masikmos** [comment]
Ohh.... i am super stupid.... need go to Application Settings and add connection strings as custom and in Storage Accounts just copy connection strings from key section....... Issue closed

**Comment by sjkp** [comment]
Not sure I understand. The last stack trace you posted, is from the KUDU site itself, it is having issues overwriting the existing web job files apparently they are locked. Usually a restart of the kudu site fixes that. 

You set the connection strings as described in this article:
https://docs.microsoft.com/en-us/azure/app-service/web-sites-configure

**Comment by sjkp** [comment]
@masikmos okay great you got it resolved. 👍
