### ISSUE TITLE
Cert Cleanup (expired)

### ISSUE THREAD

**Issue by tbasallo** [sjkp/letsencrypt-siteextension#208]
I see that in https://github.com/sjkp/letsencrypt-siteextension/commit/650e92860cea0bfc694dc4edce743837bd5ee0c7 You added code for cleaning up expired certs. But I only seeing it being called from a WebJob trigger.

Since I have version .0.8.5 running in an Azure function and it's not cleaning up, I am assuming that it's not being called automatically (I don;t think it's in that extension).

I tried following how the API is called via Kudu, but lost myself. I think I'll need to clone and try running it. 

But is there an endpoint that can be called to perform cleanup? Or is the idea to make it part of the Add/Renew process?

**Comment by sjkp** [comment]
There is no endpoint, but it is a good idea. Will add it in next release.

**Comment by Will-Bill** [comment]
Clean up is failing for me too with the below:

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.Cleanup ---> Microsoft.Rest.Azure.CloudException: Operation returned an invalid status code 'Conflict'
 at Microsoft.Azure.Management.WebSites.CertificatesOperations.<DeleteWithHttpMessagesAsync>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.<DeleteAsync>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.Delete(ICertificatesOperations operations, String resourceGroupName, String name)
 at LetsEncrypt.Azure.Core.Services.WebAppCertificateService.RemoveCertificate(WebSiteManagementClient webSiteClient, Certificate s) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\WebAppCertificateService.cs:line 104
 at LetsEncrypt.Azure.Core.Services.WebAppCertificateService.<>c__DisplayClass4_1.<RemoveExpired>b__1(Certificate s) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\WebAppCertificateService.cs:line 96
 at System.Collections.Generic.List`1.ForEach(Action`1 action)
 at LetsEncrypt.Azure.Core.Services.WebAppCertificateService.RemoveExpired(Int32 removeXNumberOfDaysBeforeExpiration) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\WebAppCertificateService.cs:line 96
 at LetsEncrypt.SiteExtension.Functions.Cleanup(TimerInfo timerInfo) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 73
 at lambda_method(Closure , Functions , Object[] )
 at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of inner exception stack trace ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__10.MoveNext()

**Comment by obrousseau** [comment]
It is failing for me too, with the same stack trace as above. @sjkp : Can you help out here? :)
