### ISSUE TITLE
(401) Unauthorized --> Invalid client secret is provided

### ISSUE THREAD

**Issue by InteXX** [sjkp/letsencrypt-siteextension#227]
Certificates are suddenly not renewing when previously they had been for about the past year. I'm getting this exception when attempting to update the configuration from the Kudu page:

    Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException:
      AADSTS70002: Error validating credentials.
      AADSTS50012: Invalid client secret is provided.
      Trace ID: d22fd214-e2b3-46e0-8a61-bf7212120000
      Correlation ID: 172afb65-367f-4733-9df8-f116c7090406
      Timestamp: 2018-07-24 21:01:55Z
        ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
        at System.Net.HttpWebRequest.GetResponse()
        at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
        --- End of inner exception stack trace ---
        at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
        at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, ClientCredential clientCredential)
        at LetsEncrypt.Azure.Core.ArmHelper.GetToken(IAzureEnvironment model) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 41
        at LetsEncrypt.Azure.Core.ArmHelper.GetWebSiteManagementClient(IAzureWebAppEnvironment model) in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 19
        at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model) ErrorCode: invalid_client StatusCode: 401

I've updated to the latest version. Has Azure tightened security with this as a result?

Also: how do I get to the log files that I frequently see folks referring to here?

**Comment by InteXX** [comment]
OK, this problem is solved [here](https://github.com/sjkp/letsencrypt-siteextension/issues/117) and [here](https://www.netiq.com/communities/cool-solutions/creating-application-client-id-client-secret-microsoft-azure-new-portal/). But the issue isn't quite yet ready to close.

I'm still wondering how to get to those juicy logs everyone's talking about.

**Comment by sjkp** [comment]
You can read about how to enable logging here:
https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-debug

**Comment by InteXX** [comment]
Sounds good, thanks!
