### ISSUE TITLE
Null reference exception in CertificateManager when trying to renew certificate

### ISSUE THREAD

**Issue by xt0rted** [sjkp/letsencrypt-siteextension#232]
Two days ago the `RenewCertificate` task started failing on one of my sites. I was on version 0.8.5 so I just updated to 0.8.7 and the error is still happening.

I haven't changed anything on this site since the last time the certificate was renewed so I'm not sure what may be causing this.

```
Exception while executing function: Functions.RenewCertificate
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LetsEncrypt.Azure.Core.CertificateManager.<RenewCertificate>d__10.MoveNext() in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LetsEncrypt.SiteExtension.Functions.<RenewCertificate>d__1.MoveNext() in c:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
```

The line it's referring to is https://github.com/sjkp/letsencrypt-siteextension/blob/a41b201020fa57ae097a6228e90a9081ce3fa882/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L143-L153

**Comment by xt0rted** [comment]
This is interesting, `D:\home\data\letsencrypt\` was empty. After copying the `settings.json` from my other site the job ran successfully.

**Comment by sjkp** [comment]
@xt0rted  thanks for letting me know.

**Comment by xt0rted** [comment]
It might be helpful to log if the settings file is found and/or used.
