### ISSUE TITLE
Upgrade Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#258]
`LetsEncrypt.Azure.Core` is dependent on `Microsoft.IdentityModel.Clients.ActiveDirectory` version `2.28.1` which is over 2 years old and the API has been broken since then so it can't be upgraded with a binding redirect.

Ideally, an update of all NuGet packages would be performed, but this specific package creates a messy dependency tree (because the API changed some need >=3 and some <3).

**Comment by ohadschn** [comment]
I just found another dependency that changed API:  [`Microsoft.Azure.Management.Websites`](https://www.nuget.org/packages/Microsoft.Azure.Management.WebSites) (it went from prerelease to stable). If you upgrade it you get:

```
System.MethodAccessException: Attempt by method 'LetsEncrypt.Azure.Core.Services.WebAppCertificateService.Install(LetsEncrypt.Azure.Core.Models.ICertificateInstallModel)' to access method 'Microsoft.Azure.Management.WebSites.Models.Resource.set_Name(System.String)' failed.
   at LetsEncrypt.Azure.Core.Services.WebAppCertificateService.Install(ICertificateInstallModel model)
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
```
