### ISSUE TITLE
Retry on transient errors

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#267]
I recently encountered the exception below, due to a 400 Bad Request returned by my web app. Retrying resolved the issue, which leads me to suggest some basic retry mechanism in `LetsEncrypt.Azure.Core`.

```[11/01/2018 00:00:22 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:22:  - AuthenticationContext: ADAL .NET with assembly version '2.28.3.860', file version '2.28.31117.1411' and informational version '78bd21073cfd91768d97894ace1ba90c5b904eec' is running...
[11/01/2018 00:00:22 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:22: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - AcquireTokenHandlerBase: === Token Acquisition started:
[11/01/2018 00:00:22 > 60e954: INFO] 	Authority: https://login.windows.net/ohad188gmail.onmicrosoft.com/
[11/01/2018 00:00:22 > 60e954: INFO] 	Resource: https://management.core.windows.net/
[11/01/2018 00:00:22 > 60e954: INFO] 	ClientId: c35b8f71-01ce-429c-accc-e1ba5fcff632
[11/01/2018 00:00:22 > 60e954: INFO] 	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (0 items)
[11/01/2018 00:00:22 > 60e954: INFO] 	Authentication Target: Client
[11/01/2018 00:00:22 > 60e954: INFO] 	
[11/01/2018 00:00:23 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:22: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - TokenCache: Looking up cache for a token...
[11/01/2018 00:00:23 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:22: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - TokenCache: No matching token was found in the cache
[11/01/2018 00:00:23 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:23: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - TokenCache: Storing token in the cache...
[11/01/2018 00:00:23 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:23: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - TokenCache: An item was stored in the cache
[11/01/2018 00:00:23 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:23: 0f8593c9-6350-4e63-84a2-0b9b700c9149 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
[11/01/2018 00:00:23 > 60e954: INFO] 	Access Token Hash: ugJn1LgNfqGaBxM1dQzLMS1IDlvGKmAELfN/aebWcFs=
[11/01/2018 00:00:23 > 60e954: INFO] 	Refresh Token Hash: [No Refresh Token]
[11/01/2018 00:00:23 > 60e954: INFO] 	Expiration Time: 11/01/2018 01:00:23 +00:00
[11/01/2018 00:00:23 > 60e954: INFO] 	User Hash: null
[11/01/2018 00:00:23 > 60e954: INFO] 	
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Staring add certificate
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - AcquireTokenHandlerBase: === Token Acquisition started:
[11/01/2018 00:00:26 > 60e954: INFO] 	Authority: https://login.windows.net/ohad188gmail.onmicrosoft.com/
[11/01/2018 00:00:26 > 60e954: INFO] 	Resource: https://management.core.windows.net/
[11/01/2018 00:00:26 > 60e954: INFO] 	ClientId: c35b8f71-01ce-429c-accc-e1ba5fcff632
[11/01/2018 00:00:26 > 60e954: INFO] 	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 items)
[11/01/2018 00:00:26 > 60e954: INFO] 	Authentication Target: Client
[11/01/2018 00:00:26 > 60e954: INFO] 	
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - TokenCache: Looking up cache for a token...
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - TokenCache: An item matching the requested resource was found in the cache
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - TokenCache: 59.9570071533333 minutes left until token in cache expires
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - TokenCache: A matching item (access token or refresh token or both) was found in the cache
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 11/01/2018 00:00:26: 9a1488f0-5733-4a69-a6fa-4222c769187b - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
[11/01/2018 00:00:26 > 60e954: INFO] 	Access Token Hash: ugJn1LgNfqGaBxM1dQzLMS1IDlvGKmAELfN/aebWcFs=
[11/01/2018 00:00:26 > 60e954: INFO] 	Refresh Token Hash: [No Refresh Token]
[11/01/2018 00:00:26 > 60e954: INFO] 	Expiration Time: 11/01/2018 01:00:23 +00:00
[11/01/2018 00:00:26 > 60e954: INFO] 	User Hash: null
[11/01/2018 00:00:26 > 60e954: INFO] 	
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Add certificate for acmeConfig hostname www.howlongtobeatsteam.com, howlongtobeatsteam.com
[11/01/2018 00:00:26 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : RequestAndInstallInternal
[11/01/2018 00:00:27 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Loading Signer from D:\home\siteextensions\letsencrypt\config\httpsacme-v01.api.letsencrypt.org\Signer
[11/01/2018 00:00:28 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 
[11/01/2018 00:00:28 > 60e954: INFO] Getting AcmeServerDirectory
[11/01/2018 00:00:28 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Loading Registration from D:\home\siteextensions\letsencrypt\config\httpsacme-v01.api.letsencrypt.org\Registration
[11/01/2018 00:00:50 > 60e954: INFO] 
[11/01/2018 00:00:50 > 60e954: INFO] Authorizing Identifier www.howlongtobeatsteam.com Using Challenge Type http-01
[11/01/2018 00:00:52 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Authorizing Identifier www.howlongtobeatsteam.com Using Challenge Type http-01
[11/01/2018 00:00:52 > 60e954: INFO]  Answer should now be browsable at http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg
[11/01/2018 00:00:52 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Answer should now be browsable at http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg
[11/01/2018 00:00:54 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Checking status OK
[11/01/2018 00:00:54 > 60e954: INFO]  Submitting answer
[11/01/2018 00:00:54 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Submitting answer
[11/01/2018 00:00:55 > 60e954: INFO]  Refreshing authorization attempt 1
[11/01/2018 00:00:55 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Refreshing authorization attempt 1
[11/01/2018 00:00:57 > 60e954: INFO]  Authorization Result: invalid
[11/01/2018 00:00:57 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Auth Result invalid
[11/01/2018 00:00:57 > 60e954: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Authorization Failed invalid
[11/01/2018 00:00:58 > 60e954: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Full Error Details {"IdentifierPart":{"Type":"dns","Value":"www.howlongtobeatsteam.com"},"IdentifierType":"dns","Identifier":"www.howlongtobeatsteam.com","Uri":"https://acme-v01.api.letsencrypt.org/acme/authz/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM","Status":"invalid","Expires":"2018-11-08T00:00:50Z","Challenges":[{"ChallengePart":{"Type":"tls-sni-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122418","Token":"nwtR51YeWVi_BG_Z8dttxH0eZDCktkn8xWOOv-0-Z8o","Status":"invalid","Validated":null,"Error":null},"Challenge":null,"Type":"tls-sni-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122418","Token":"nwtR51YeWVi_BG_Z8dttxH0eZDCktkn8xWOOv-0-Z8o","Status":"invalid","OldChallengeAnswer":{"Key":null,"Value":null},"ChallengeAnswerMessage":null,"HandlerName":null,"HandlerHandleDate":null,"HandlerCleanUpDate":null,"SubmitDate":null,"SubmitResponse":null},{"ChallengePart":{"Type":"dns-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122424","Token":"X8OXjZ4CPu5LUeoMujq83SIucFCBiX_5yy-ArSqVwjk","Status":"invalid","Validated":null,"Error":null},"Challenge":null,"Type":"dns-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122424","Token":"X8OXjZ4CPu5LUeoMujq83SIucFCBiX_5yy-ArSqVwjk","Status":"invalid","OldChallengeAnswer":{"Key":null,"Value":null},"ChallengeAnswerMessage":null,"HandlerName":null,"HandlerHandleDate":null,"HandlerCleanUpDate":null,"SubmitDate":null,"SubmitResponse":null},{"ChallengePart":{"Type":"tls-alpn-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122428","Token":"2qM7y8PN2CzbBVdQpQnni1XUtXlHVkC6BAe6gmNOIe8","Status":"invalid","Validated":null,"Error":null},"Challenge":null,"Type":"tls-alpn-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122428","Token":"2qM7y8PN2CzbBVdQpQnni1XUtXlHVkC6BAe6gmNOIe8","Status":"invalid","OldChallengeAnswer":{"Key":null,"Value":null},"ChallengeAnswerMessage":null,"HandlerName":null,"HandlerHandleDate":null,"HandlerCleanUpDate":null,"SubmitDate":null,"SubmitResponse":null},{"ChallengePart":{"Type":"http-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122433","Token":"dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg","Status":"invalid","Validated":null,"Error":{"type":"urn:acme:error:connection","detail":"Fetching https://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg: Error getting validation data","status":"400"},"validationRecord":[{"url":"http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg","hostname":"www.howlongtobeatsteam.com","port":"80","addressesResolved":["104.209.197.87"],"addressUsed":"104.209.197.87"},{"url":"https://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg","hostname":"www.howlongtobeatsteam.com","port":"443","addressesResolved":["104.209.197.87"]}]},"Challenge":null,"Type":"http-01","Uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM/8827122433","Token":"dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg","Status":"invalid","OldChallengeAnswer":{"Key":null,"Value":null},"ChallengeAnswerMessage":null,"HandlerName":null,"HandlerHandleDate":null,"HandlerCleanUpDate":null,"SubmitDate":null,"SubmitResponse":null}],"Combinations":[[3],[2],[0],[1]]}
[11/01/2018 00:00:58 > 60e954: INFO] The ACME server was probably unable to reach http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg
[11/01/2018 00:00:58 > 60e954: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Unable to reach http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg
[11/01/2018 00:00:58 > 60e954: INFO] 
[11/01/2018 00:00:58 > 60e954: INFO] Check in a browser to see if the answer file is being served correctly.
[11/01/2018 00:00:58 > 60e954: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Encountered exception: System.Exception: The Lets Encrypt ACME server was probably unable to reach http://www.howlongtobeatsteam.com/.well-known/acme-challenge/dq8gOxFY3ImAXBATD9N05mVb0k0RlQOhQOgLQ8XTJJg view error report from Lets Encrypt at https://acme-v01.api.letsencrypt.org/acme/authz/NnfU51jv83ordqJTomVslYY8XlRbNpCu2LNv5hSeNjM for more information
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__12.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[11/01/2018 00:00:58 > 60e954: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<Renew>d__6.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 73
[11/01/2018 00:00:58 > 60e954: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/01/2018 00:00:58 > 60e954: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 35```

**Comment by sjkp** [comment]
Yes, you are right. Will add polly to the new version.
