### ISSUE TITLE
Unable to create new certs

### ISSUE THREAD

**Issue by ElanHasson** [sjkp/letsencrypt-siteextension#272]
I get an asp.net error after installation when attempting to setup certs for the domain.

```

[SocketException (0x274c): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 168.61.217.128:80]    System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult) +8652705    System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) +91    System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) +307  [WebException: Unable to connect to the remote server]    System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +729    System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +77  [HttpRequestException: An error occurred while sending the request.]    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    LetsEncrypt.Azure.Core.Services.<Authorize>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\BaseHttpAuthorizationChallengeProvider.cs:86    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    LetsEncrypt.Azure.Core.Services.<Authorize>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\BaseHttpAuthorizationChallengeProvider.cs:131    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    LetsEncrypt.Azure.Core.Services.<RequestCertificate>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:43    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    LetsEncrypt.Azure.Core.<RequestInternalAsync>d__13.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:192    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    LetsEncrypt.Azure.Core.<RequestAndInstallInternalAsync>d__14.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:205    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    LetsEncrypt.SiteExtension.Controllers.<Install>d__7.MoveNext() in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:229    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +92    System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +188    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38    System.Web.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar) +212    System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +166
--



[SocketException]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 168.61.217.128:80
--
  | at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
  | at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
  | at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
  | [WebException]: Unable to connect to the remote server
  | at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
  | at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
  | [HttpRequestException]: An error occurred while sending the request.
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\BaseHttpAuthorizationChallengeProvider.cs:line 86
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\BaseHttpAuthorizationChallengeProvider.cs:line 131
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:line 43
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__13.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 192
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__14.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 205
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at LetsEncrypt.SiteExtension.Controllers.HomeController.<Install>d__7.MoveNext() in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:line 229
  | --- End of stack trace from previous location where exception was thrown ---
  | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  | at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
  | at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
  | at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
  | at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
  | at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
  | at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
  | at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
  | at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
  | at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
  | at System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
  | at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)


```

**Comment by ElanHasson** [comment]
Disregard. One host name didn't resolve.
