### ISSUE TITLE
Web Job won't restart (A host ID must be between 1 and 32 characters)

### ISSUE THREAD

**Issue by mkultra-z** [sjkp/letsencrypt-siteextension#284]
Hi there,

I've installed the latest version `0.8.10` and am now encountering an errors when attempting to start the WebJob. 

```
[01/10/2019 00:46:08 > 327034: ERR ] Unhandled Exception: System.ArgumentException: A host ID must be between 1 and 32 characters, contain only lowercase letters, numbers, and dashes, not start or end with a dash, and not contain consecutive dashes.
[01/10/2019 00:46:08 > 327034: ERR ] Parameter name: value
[01/10/2019 00:46:08 > 327034: ERR ]    at Microsoft.Azure.WebJobs.JobHostConfiguration.set_HostId(String value)
[01/10/2019 00:46:08 > 327034: ERR ]    at LetsEncrypt.SiteExtension.WebJob.Program.Main() in D:\a\1\s\LetsEncrypt.SiteExtension.WebJob\Program.cs:line 28
```

I searched through your documentation and couldn't find anything mentioning a HostId.

What is the HostId? Is this something I should set? Where would I set this?

Any help you can provided will be greatly appreciated.
Cheers,

**Comment by mkultra-z** [comment]
Ahhhh never mind my deployment slot had parenthesis in it 🤦
