### ISSUE TITLE
WebJob Error

### ISSUE THREAD

**Issue by alexiordan** [sjkp/letsencrypt-siteextension#322]
Hi,
I followed the tutorials [here ](https://www.tecklyfe.com/how-to-setup-lets-encrypt-ssl-certificates-for-an-azure-web-app/)and [here](https://www.hanselman.com/blog/SecuringAnAzureAppServiceWebsiteUnderSSLInMinutesWithLetsEncrypt.aspx).
Certificates seem to be installed OK, however when I take a look on  my app events I see following error: each 1 min 25 sec.
What should I do?

```
Application: LetsEncrypt.SiteExtension.WebJob.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.Azure.WebJobs.Host.Storage.StorageAccountExtensions.AssertTypeOneOf(Microsoft.Azure.WebJobs.Host.Storage.IStorageAccount, Microsoft.Azure.WebJobs.Host.Storage.StorageAccountType[])
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider+&lt;CreateAndValidateAccountAsync&gt;d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions+&lt;CreateJobHostContextAsync&gt;d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.JobHost+&lt;InitializeHostAsync&gt;d__44.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.JobHost+&lt;StartAsyncCore&gt;d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.JobHost.Start()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at LetsEncrypt.SiteExtension.WebJob.Program.Main()`
```

**Comment by alexiordan** [comment]
SOLVED:

Taking a deeper look into WebJob Details here:
AppService > Advanced Tools(kudu) > (in the top menu) Tools > WebJobs dashboard >letsencrypt(letsencrypt.siteextension.job) > Toggle Output

A new message was revealed: `Unhandled Exception: System.InvalidOperationException: Storage account 'zenparkingstorage' is of unsupported type 'Blob-Only/ZRS'. Supported types are 'General Purpose'`

From here on, I choosed the right storage and it works.
