### ISSUE TITLE
Can't connect to storage account

### ISSUE THREAD

**Issue by Valkhan** [sjkp/letsencrypt-siteextension#327]
Extension version: 0.9.6

I've created both: AzureWebJobsDashboard and AzureWebJobsStorage configurations in my webapp by copy/paste from the connection string from the keys in my storage account, when I check the webjob i get this error:

I also tried:

1. renewing the keys with no success
1. reinstalling the extension
1. restarting web app

> [08/28/2019 01:44:55 > 643da0: ERR ] Unhandled Exception: System.InvalidOperationException: Invalid storage account 'MYSTORAGEACCOUNTNAME'. Please make sure your credentials are correct. ---> Microsoft.WindowsAzure.Storage.StorageException: Requested value 'DELETE,GET,HEAD,POST,MERGE,OPTIONS,PUT,PATCH' was not found. ---> System.ArgumentException: Requested value 'DELETE,GET,HEAD,POST,MERGE,OPTIONS,PUT,PATCH' was not found.
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.ServiceProperties.<ReadCorsPropertiesFromXml>b__4(XElement rule) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\ServiceProperties.cs:line 606
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.ServiceProperties.ReadCorsPropertiesFromXml(XElement element) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\ServiceProperties.cs:line 603
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.ServiceProperties.FromServiceXml(XDocument servicePropertiesDocument) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\ServiceProperties.cs:line 267
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ReadServiceProperties(Stream inputStream) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 150
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient.<GetServicePropertiesImpl>b__1a(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobClient.cs:line 1295
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<RunPostProcessAsync>d__e`1.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 495
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<EndOperationAsync>d__b`1.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 444
[08/28/2019 01:44:55 > 643da0: ERR ]    --- End of inner exception stack trace ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 51
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient.EndGetServiceProperties(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobClient.cs:line 906
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 69
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator.<ValidateCredentialsAsyncCore>d__1.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ]    --- End of inner exception stack trace ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator.<ValidateCredentialsAsyncCore>d__1.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator.<ValidateCredentialsAsync>d__0.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<CreateAndValidateAccountAsync>d__24.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.<CreateJobHostContextAsync>d__1.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<InitializeHostAsync>d__44.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__25.MoveNext()
[08/28/2019 01:44:55 > 643da0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.JobHost.Start()
[08/28/2019 01:44:55 > 643da0: ERR ]    at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
[08/28/2019 01:44:55 > 643da0: ERR ]    at LetsEncrypt.SiteExtension.WebJob.Program.Main() in D:\a\1\s\LetsEncrypt.SiteExtension.WebJob\Program.cs:line 31
[08/28/2019 01:44:55 > 643da0: SYS ERR ] Job failed due to exit code -532462766
[08/28/2019 01:44:55 > 643da0: SYS INFO] Process went down, waiting for 60 seconds
[08/28/2019 01:44:55 > 643da0: SYS INFO] Status changed to PendingRestart

**Comment by ewwwgiddings** [comment]
Did you ever find a solution to this? I have the same exact issue

**Comment by ohadschn** [comment]
@ewwwgiddings you know Microsoft has free built in SSL certs by now right? https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate#create-a-free-managed-certificate

**Comment by ewwwgiddings** [comment]
@ohadschn No I had no idea. That's really helpful thank you! Looks like one limitation may keep me using this instead of converting - the no wildcards. Since this could support it - and I already have it set up - I might as well keep plugging away with this on the chance I make a subdomain (which I could see a few instances I'd want to in the future). For some other App Services though this is huge. I appreciate you posting that!

**Comment by ewwwgiddings** [comment]
The answer was CORs if anyone ever sees this in the future. I tried allowing my domain plus my Kudo domain and it was still being blocked. Did * (which thankfully isn't a security issue for the storage) and it worked. If anyone ever knows what origin to put that would be huge.

**Comment by ewwwgiddings** [comment]
But I guess @ohadschn if I do a subdomain I might want to have that be its own App Service anyway so I could use the Azure one in that way.

**Comment by ohadschn** [comment]
@ewwwgiddings wildcards are not supported in this extension either:

https://github.com/sjkp/letsencrypt-siteextension#known-issues
> Wildcard domains are not supported, (and will not be supposed in the site-extension), if you are interested in wildcard support check https://github.com/sjkp/letsencrypt-azure

Or if you prefer to stay with a WebJob approach, I created this: https://github.com/ohadschn/letsencrypt-webapp-renewer
