### ISSUE TITLE
Internationalized Domain Names (IDNs) broken in certes-based letsencrypt.azure.core

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#340]
Specifically, I'm hitting this with the latest version (`1.0.4`).

If I use the Unicode name (`אהד`):
```
urn:ietf:params:acme:error:rejectedIdentifier: Error finalizing order :: Cannot issue for "???.azuredns.site": Invalid character in DNS name
   at Certes.Acme.IAcmeHttpClientExtensions.<Post>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.Acme.OrderContext.<Finalize>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.IOrderContextExtensions.<Finalize>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.IOrderContextExtensions.<Generate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__15.MoveNext()
```

If I use the punycode name (`xn--4dbgc`), the above succeeds but then I get:
```
Response: PUT https://management.azure.com/subscriptions/[REDACTED]/resourceGroups/new-app-cert-renew-test/providers/Microsoft.Web/sites/new-app-cert-renew-test?api-version=2018-02-01, headers x-ms-client-request-id = [REDACTED],accept-language = en-US,User-Agent = FxVersion/4.7.3468.0|OSName/Windows|OSVersion/6.2.9200.0|Microsoft.Azure.Management.WebSites.WebSiteManagementClient/2.1.0
{"Code":"NotFound","Message":"Hostname 'xn--4dbgc.azuredns.site' does not exist.","Target":null,"Details":[{"Message":"Hostname 'xn--4dbgc.azuredns.site' does not exist."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"04020","MessageTemplate":"Hostname '{0}' does not exist.","Parameters":["xn--4dbgc.azuredns.site"],"Code":"NotFound","Message":"Hostname 'xn--4dbgc.azuredns.site' does not exist."}}],"Innererror":null}
```

It looks like the Azure Management client expects the Unicode name whereas the Certes client expects the punycode name. So I believe the correct fix here would be to punycode the host name before it's passed to Certes.

**Comment by justdmitry** [comment]
Same for me, with russian (cyrillic) domain name.

**Comment by ohadschn** [comment]
@justdmitry I have a workaround. Make sure that the **first** name on the `letsencrypt:Hostnames` configuration is non-IDN (create a dummy one if needed). That would put the IDN host names in the cert's Subject Alternative Names, which is handled correctly in the code: https://github.com/sjkp/letsencrypt-siteextension/blob/ff74be140e476418d371e9f3e451ebc5624c1ddb/LetsEncrypt.SiteExtension.Core/Services/ACMEService.cs#L52

**Comment by justdmitry** [comment]
@ohadschn wow, it works great, thank you.
