### ISSUE TITLE
Azure.WebJobs.Host.FunctionInvocationException - Functions.AddCertificate

### ISSUE THREAD

**Issue by MyNameIsCeeJay** [sjkp/letsencrypt-siteextension#400]
Experiencing a Function Failure that I'm not sure if I need to be concerned about or not. 

The RenewCert and Cleanup Functions are successful, but not the AddCertificate Function, even though the certificate installs successfully and I'm met with "Certificate was added with success" green-bar notification.

Azure Let's Encrypt
Version **1.0.6**
By SJKP

`Exception while executing function: Functions.AddCertificate
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.AddCertificate ---> System.InvalidOperationException : A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at async LetsEncrypt.Azure.Core.CertificateManager.AddCertificate() at D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs : 116
   at LetsEncrypt.SiteExtension.Functions.AddCertificate(TimerInfo timerInfo,String input,String& output) at D:\a\1\s\LetsEncrypt.SiteExtension.WebJob\Functions.cs : 50
   at lambda_method(Closure ,Functions ,Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception`

**Comment by MyNameIsCeeJay** [comment]
![image](https://user-images.githubusercontent.com/53047473/151357695-6ebee85f-49fd-40ce-a20a-28ad5a99f5bd.png)
