### ISSUE TITLE
Can't install certificate on the final step

### ISSUE THREAD

**Issue by Lanayx** [sjkp/letsencrypt-siteextension#9]
Here are the streaming logs of the error I get on /Home/Install. (staging checkbox enabled)

2016-01-21T11:11:52  PID[7808] Error       Microsoft.Rest.Azure.CloudException: Certificate 9B2717DAAD8277293B74FDF906F36CB12C2E465F was not found.
   at Microsoft.Azure.Management.WebSites.SitesOperations.<BeginCreateOrUpdateSiteWithHttpMessagesAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.<BeginCreateOrUpdateSiteAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.BeginCreateOrUpdateSite(ISitesOperations operations, String resourceGroupName, String name, Site siteEnvelope, String skipDnsRegistration, String skipCustomDomainVerification, String forceDnsRegistration, String ttlInSeconds)
   at LetsEncrypt.SiteExtension.Functions.Install(Target target, String pfxFilename, X509Certificate2 certificate)
   at LetsEncrypt.SiteExtension.Functions.Auto(Target binding)
   at LetsEncrypt.SiteExtension.Functions.RequestAndInstallInternal(Target target)

The thumbprint is visible on /Home/Hostname page, but invisible in the azure portal.

**Comment by sjkp** [comment]
Are you app hosting plan and web app in the same resource group?

**Comment by Lanayx** [comment]
You are right, sites are in different resource groups and hosting plan is the same to reduce cost. Can this be overcome?

**Comment by sjkp** [comment]
@Lanayx yes - i will look into it. I understand that it is fairly common, so would be nice to handle that scenario.
